name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.0
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.0+1
  firebase_database: ^3.1.1
  google_sign_in: ^4.1.1
#  flutter_blue: ^0.6.3+1
#  video_player: ^0.10.6
  translator: ^0.1.4
  firebase_storage: ^3.1.1
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+1
  image_picker: ^0.6.3+1
  cached_network_image: ^2.0.0
  flutter_icons: ^1.0.0+1
  giphy_picker: ^1.0.4
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1


dev_dependencies:
  flutter_driver:
    sdk: flutter
  #   test: any

flutter:
  uses-material-design: true

  assets:
  - images/
